- name: Create cache directory
  become: true
  file: path={{ docker_proxy_cache_path  }} state=directory mode=0755 recurse=true

- name: Copy the ssl certificates
  become: true
  copy:
    src: "{{ item }}"
    dest: "{{ docker_proxy_ssl_host_path }}/{{ item }}"
  with_items:
    - certificate.pem
    - key.pem
  when:
    - docker_proxy_ssl_enabled | bool
    - docker_proxy_ssl_copy_certs | bool

- name: Print current cache directory size information
  become: true
  command: du -hs {{ docker_proxy_cache_path  }}

- name: Pull proxy container
  become: true
  command: >
    docker pull esailors/aws-ecr-http-proxy:{{ docker_proxy_version }}
  tags:
    - pull-image

- name: Remove previous proxy container
  become: true
  command: docker rm -fv docker-registry-proxy
  ignore_errors: true

- name: Clear local cache
  become: true
  command: rm -rf {{ docker_proxy_cache_path  }}
  when: docker_proxy_clear_cache|bool

- name: Run new docker registry proxy container
  become: true
  command: >
    docker run -d
      --name docker-registry-proxy
      --net host
      --restart=unless-stopped

      -v {{ docker_proxy_cache_path }}:/cache

      {% if docker_proxy_ssl_enabled | bool %}
      -v {{ docker_proxy_ssl_host_path }}/{{ docker_proxy_ssl_host_cert_name }}:{{ docker_proxy_ssl_container_path }}/certificate.pem
      -v {{ docker_proxy_ssl_host_path }}/{{ docker_proxy_ssl_host_key_name }}:{{ docker_proxy_ssl_container_path }}/key.pem

      -e ENABLE_SSL=true
      -e REGISTRY_HTTP_TLS_KEY={{ docker_proxy_ssl_container_path }}/key.pem
      -e REGISTRY_HTTP_TLS_CERTIFICATE={{ docker_proxy_ssl_container_path }}/certificate.pem
      {% endif %}

      -e RESOLVER={{ docker_proxy_backend_resolver }}
      -e PORT=5000
      -e UPSTREAM={{ docker_proxy_backend_schema }}://{{ docker_proxy_backend }}
      -e AWS_ACCESS_KEY_ID={{ docker_proxy_ecr_access_id }}
      -e AWS_SECRET_ACCESS_KEY={{ docker_proxy_ecr_secret_key }}
      -e AWS_REGION={{ docker_proxy_ecr_region }}

      esailors/aws-ecr-http-proxy:{{ docker_proxy_version }}
